apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: eglobalshop
  labels:
    app: postgres-db
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres-db
