apiVersion: v1
kind: Service
metadata:
  name: nats-server
  namespace: eglobalshop
  labels:
    app: nats-server
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: 4222
      protocol: TCP
      name: nats
    - port: 8222
      targetPort: 8222
      protocol: TCP
      name: monitoring
  selector:
    app: nats-server
---
apiVersion: v1
kind: Service
metadata:
  name: nats-monitoring
  namespace: eglobalshop
  labels:
    app: nats-server
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: NodePort
  ports:
    - port: 8222
      targetPort: 8222
      nodePort: 30042
      protocol: TCP
      name: monitoring
  selector:
    app: nats-server
