apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-config
  namespace: eglobalshop
  labels:
    app: customers-service
    app.kubernetes.io/name: customers
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_HTTP_PORTS: "7000"
  ConnectionStrings__Database: "Host=postgres-db;Port=5432;Database=eGlobalShop.Customers;Username=postgres;Password=postgres;Include Error Detail=true"
  NATS_SERVER_URL: "nats://nats-server:4222"
