apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: eglobalshop
  labels:
    app: pgadmin
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: database-admin
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        app.kubernetes.io/name: pgadmin
        app.kubernetes.io/component: database-admin
    spec:
      containers:
        - name: pgadmin
          image: docker.io/dpage/pgadmin4:latest
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: pgadmin-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
