services:
  customers-service:
    image: customers-service
    container_name: customers-service
    build:
      context: .
      dockerfile: Customers/Dockerfile
    ports:
      - "8000:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8000
      ConnectionStrings__Database: "Host=postgres-db;Port=5432;Database=eGlobalShop.Customers;Username=postgres;Password=postgres;Include Error Detail=true"
      NATS_SERVER_URL: nats://nats:4222
    depends_on:
      - postgres-db
      - nats-server

  order-service:
    image: order-service
    container_name: order-service
    build:
      context: .
      dockerfile: Orders/Dockerfile
    ports:
      - "7000:7000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 7000
      ConnectionStrings__Database: "Host=postgres-db;Port=5432;Database=eGlobalShop.Orders;Username=postgres;Password=postgres;Include Error Detail=true"
      NATS_SERVER_URL: nats://nats:4222
    depends_on:
      - postgres-db
      - nats-server

  inventory-service:
    image: inventory-service
    container_name: inventory-service
    build:
      context: .
      dockerfile: Inventory/Dockerfile
    ports:
      - "6000:6000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 6000
      ConnectionStrings__Database: "Host=postgres-db;Port=5432;Database=eGlobalShop.Inventory;Username=postgres;Password=postgres;Include Error Detail=true"
      NATS_SERVER_URL: nats://nats:4222
    depends_on:
      - postgres-db
      - nats-server

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eGlobalShop.Customers
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eGlobalShop.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
      - nats-server
  nats-server:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222" # HTTP monitoring port

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    restart: unless-stopped

volumes:
  seq-data:
