apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: eglobalshop
  labels:
    app: billing-service
    app.kubernetes.io/name: billing
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: billing-service
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service-nodeport
  namespace: eglobalshop
  labels:
    app: billing-service
    app.kubernetes.io/name: billing
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 9000
      protocol: TCP
      name: http
  selector:
    app: billing-service
