### Create a Category
POST http://localhost:6000/categories
Content-Type: application/json

{
  "name": "Electronics",
  "description": "Electronics category."
}

### Create a Product
POST http://localhost:6000/products
Content-Type: application/json

{
  "name": "SONY TV",
  "description": "SONY Smart TV",
  "price": 19.99,
  "quantity": 5000,
  "categoryId": 1
}

### Update a Product
PUT http://localhost:6000/products
Content-Type: application/json

{
  "productId": "0196f6ab-1254-7c3f-8732-3c4c723efd22",
  "quantity": 5
}


### Get a Product by ID
GET http://localhost:6000/products/a9b0c1d2-e3f4-4a5b-6c7d-8e9f0a1b2c3d
Accept: application/json

### Get All Products
GET http://localhost:6000/products
Accept: application/json

