### 1. Get all Customers
GET http://localhost:8000/customers
Accept: application/json

### 2. Get Customer by Id
GET http://localhost:8000/customers/94b84094-2f06-4b8c-b483-944698f1bd58
Accept: application/json

### 3. Create a new Customer
POST http://localhost:8000/customers
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "sdbala@example.com",
  "phoneNumber": "123-456-7890",
  "dateOfBirth": "1990-01-01",
  "address": "123 Main Street",
  "city": "Sample City",
  "state": "Sample State",
  "zipCode": "12345"
}

