apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: eglobalshop
  labels:
    app: shipping-service
    app.kubernetes.io/name: shipping
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: shipping-service
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service-nodeport
  namespace: eglobalshop
  labels:
    app: shipping-service
    app.kubernetes.io/name: shipping
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30400
      protocol: TCP
      name: http
  selector:
    app: shipping-service
