apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: eglobalshop
  labels:
    app: orders-service
    app.kubernetes.io/name: orders
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
        app.kubernetes.io/name: orders
        app.kubernetes.io/component: microservice
    spec:
      containers:
        - name: orders
          image: localhost/eglobalshop-order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: orders-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
      restartPolicy: Always
