apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: eglobalshop
  labels:
    app: orders-service
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: orders-service
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service-nodeport
  namespace: eglobalshop
  labels:
    app: orders-service
    app.kubernetes.io/name: orders
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 5000
      protocol: TCP
      name: http
  selector:
    app: orders-service
