services:
  postgres-db:
    image: docker.io/library/postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eGlobalShop.Customers
    ports:
      - "5432:5432"
    networks:
      - eglobalshop-network

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eGlobalShop.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
      - nats-server
    networks:
      - eglobalshop-network

  nats-server:
    image: docker.io/library/nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222" # HTTP monitoring port
    networks:
      - eglobalshop-network

  seq:
    image: docker.io/datalust/seq:latest
    container_name: seq
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
    restart: unless-stopped
    networks:
      - eglobalshop-network

networks:
  eglobalshop-network:
    external: true
