apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: eglobalshop
  labels:
    app: pgadmin
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/component: database-admin
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30050
      protocol: TCP
      name: http
  selector:
    app: pgadmin
