apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: eglobalshop
  labels:
    app: inventory-service
    app.kubernetes.io/name: inventory
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
        app.kubernetes.io/name: inventory
        app.kubernetes.io/component: microservice
    spec:
      containers:
        - name: inventory
          image: eglobalshop-inventory-service:latest
          ports:
            - containerPort: 6000
              name: http
          envFrom:
            - configMapRef:
                name: inventory-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 6000
            initialDelaySeconds: 15
            periodSeconds: 5
      restartPolicy: Always
