apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: eglobalshop
  labels:
    app: inventory-service
    app.kubernetes.io/name: inventory
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: ClusterIP
  ports:
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: http
  selector:
    app: inventory-service
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-nodeport
  namespace: eglobalshop
  labels:
    app: inventory-service
    app.kubernetes.io/name: inventory
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: eglobalshop-microservices
spec:
  type: NodePort
  ports:
    - port: 6000
      targetPort: 6000
      nodePort: 6000
      protocol: TCP
      name: http
  selector:
    app: inventory-service
